server:
  port: 6001
spring:
  application:
    name: gateway
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
  instance:
    instance-id: gateway.com
    # 访问路径可以显示ip地址
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: provider
      path: /final/**
  ignored-services: provider # 忽略真实的服务器名，考虑到安全性,单个可以指定名字，忽略多个可以用*
  #  ignored-services: "*"
  prefix: /neu # 设置统一的公共前缀